### ISSUE TITLE
这不是还是个伪区块链吗

### ISSUE THREAD

**Issue by dulumao** [AntChainOpenLab/AntChainBridgePluginServer#2]
还是中心化的东西，就是分布db,糊弄人吧

**Comment by zouxyan** [comment]
这次开源的没有蚂蚁链的区块链部分哈，目前是跨链异构链接入的SDK，我们后面会把底层中继网络和PTC部分都开放出来

可以移步[wiki](https://github.com/AntChainOpenLab/AntChainBridgePluginSDK/wiki)了解一下，ღ( ´･ᴗ･` )比心

**Comment by zouxyan** [comment]
@dulumao 如果没有进一步问题，我先关闭了哈，可以加入我们钉群、发邮件或者开一个discussion来聊下
